#
# Copyright (C) 2025 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

LOCAL_DIR := vendor/bluefox/nx1

# Vendor DLKM kernel modules
BOARD_VENDOR_KERNEL_MODULES_LOAD := \
    fhctl.ko \
    btif_drv.ko \
    connadp.ko \
    conn_md_drv.ko \
    trace_mmstat.ko \
    mtk-cqdma.ko \
    mtk-dvfsrc-helper.ko \
    mtk-dvfsrc-devfreq.ko \
    mtk-dvfsrc-start.ko \
    mt6768_dcm.ko \
    mtk_dcm.ko \
    mtk_gpu_hal.ko \
    mtk_gpufreq_wrapper_legacy.ko \
    mtk_gpufreq_mt6768.ko \
    ged.ko \
    mali_prot_alloc_mt6768_r49.ko \
    mali_mgm_mt6768_r49.ko \
    mali_kbase_mt6768_r49.ko \
    mtk_gpu_qos.ko \
    reboot-mode.ko \
    syscon-reboot-mode.ko \
    mtk_battery_oc_throttling.ko \
    mtk_low_battery_throttling.ko \
    mtk_dynamic_loading_throttling.ko \
    mtk_md_power_throttling.ko \
    mtk_cpu_power_throttling.ko \
    mtk_peak_power_budget.ko \
    mtk_pbm.ko \
    mtk_mdpm_v1.ko \
    ccci_util_lib.ko \
    ccci_auxadc.ko \
    ccci_md_all.ko \
    ccci_fsm_scp.ko \
    sensorHub.ko \
    hwmon.ko \
    sensor_list.ko \
    accel_common.ko \
    accelhub.ko \
    gyro_common.ko \
    gyrohub.ko \
    mag_common.ko \
    maghub.ko \
    alsps_common.ko \
    alspshub.ko \
    baro_common.ko \
    barohub.ko \
    step_counter.ko \
    stepsignhub.ko \
    situation.ko \
    situationhub.ko \
    rotatvechub.ko \
    gamerotvechub.ko \
    gmagrotvechub.ko \
    gravityhub.ko \
    linearacchub.ko \
    orienthub.ko \
    uncali_acchub.ko \
    uncali_gyrohub.ko \
    uncali_maghub.ko \
    fusion.ko \
    sensor_probe.ko \
    ccci_ccif.ko \
    rps_perf.ko \
    ccmni.ko \
    ccci_cldma.ko \
    v4l2-flash-led-class.ko \
    mtk-composite.ko \
    flashlight.ko \
    flashlights-const-gpio.ko \
    mainaf.ko \
    main2af.ko \
    main3af.ko \
    subaf.ko \
    sub2af.ko \
    c2k_usb.ko \
    c2k_usb_f_via_atc.ko \
    c2k_usb_f_via_ets.ko \
    c2k_usb_f_via_modem.ko \
    mtk_u_ether.ko \
    mtk_usb_f_rndis.ko \
    sspm_v1.ko \
    mtk_power_gs_v1.ko \
    MTK_INTERNAL_SPM.ko \
    mcdi.ko \
    mtk-smi-bwc.ko \
    nvmem-mt635x-efuse.ko \
    gz_trusty_mod.ko \
    gz_ipc_mod.ko \
    gz_irq_mod.ko \
    gz_virtio_mod.ko \
    gz_tz_system.ko \
    gz_main_mod.ko \
    gz_log_mod.ko \
    trusted_mem.ko \
    mtk_heap_debug.ko \
    mtk_sec_heap.ko \
    iommu_gz.ko \
    cmdq-sec-drv.ko \
    cmdq-bdg-mailbox.ko \
    cmdq-bdg-test.ko \
    mdp_drv_mt6768.ko \
    mtk-pwm.ko \
    mtk_irtx_pwm.ko \
    mt6358-accdet.ko \
    thermal_monitor.ko \
    mediatek_static_power.ko \
    imgsensor_isp4_t.ko \
    camera_eeprom_isp4_t.ko \
    mediatek_eem.ko \
    Upower.ko \
    CPU_DVFS.ko \
    mtk_qos_legacy.ko \
    mtk_ppm_v3.ko \
    musb_boost.ko \
    mtk-sp-spk-amp.ko \
    mtk-btcvsd.ko \
    mtk-afe-external.ko \
    snd-soc-mtk-common.ko \
    snd-soc-mt6768-afe.ko \
    snd-soc-mt6358.ko \
    mt6768-mt6358.ko \
    archcounter_timesync.ko \
    camera_mem.ko \
    camera_isp_4_t.ko \
    camera_fdvt_isp40.ko \
    camera_dpe_isp40.ko \
    cam_qos_4.ko \
    ccu_isp4.ko \
    mtk-mbox.ko \
    mtk_rpmsg_mbox.ko \
    mtk_tinysys_ipi.ko \
    scp.ko \
    mt63xx-debug.ko \
    mtk_cm_mgr.ko \
    mtk_cm_mgr_mt6768.ko \
    bt_drv_connac1x.ko \
    mtk-vcu.ko \
    mtk-vcodec-common.ko \
    mtk-vcodec-dec-v1.ko \
    mtk-vcodec-enc-v1.ko \
    mtk_jpeg.ko \
    atf_logger.ko \
    uload_ind.ko \
    load_track.ko \
    mtk_perf_common.ko \
    mtk_perf_ioctl.ko \
    powerhal_cpu_ctrl.ko \
    touch_boost.ko \
    mtk_ioctl_touch_boost.ko \
    mtk_ioctl_powerhal.ko \
    sec.ko \
    mtk_disp_sec.ko \
    t-base-tui.ko \
    cfg80211.ko \
    mac80211.ko \
    arm_dsu_pmu.ko \
    cpufreq_sugov_ext.ko \
    scheduler.ko \
    mtk_em.ko \
    cpuqos_ext.ko \
    eas_ext.ko \
    widevine_driver.ko \
    mtk_fpsgo.ko \
    fpsgo.ko

BOARD_VENDOR_KERNEL_MODULES := \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/CPU_DVFS.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/MTK_INTERNAL_SPM.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/Upower.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/accel_common.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/accelhub.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/alsps_common.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/alspshub.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/archcounter_timesync.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/arm_dsu_pmu.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/atf_logger.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/baro_common.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/barohub.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/bt_drv_connac1x.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/btif_drv.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/c2k_usb.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/c2k_usb_f_via_atc.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/c2k_usb_f_via_ets.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/c2k_usb_f_via_modem.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/cam_qos_4.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/camera_dpe_isp40.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/camera_eeprom_isp4_t.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/camera_fdvt_isp40.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/camera_isp_4_t.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/camera_mem.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/ccci_auxadc.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/ccci_ccif.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/ccci_cldma.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/ccci_fsm_scp.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/ccci_md_all.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/ccci_util_lib.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/ccmni.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/ccu_isp4.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/cfg80211.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/cmdq-bdg-mailbox.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/cmdq-bdg-test.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/cmdq-sec-drv.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/cmdq-test.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/conn_md_drv.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/connadp.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/cpufreq_sugov_ext.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/cpuqos_ext.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/eas_ext.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/fhctl.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/flashlight.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/flashlights-const-gpio.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/fmradio_drv_mt6631.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/fpsgo.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/fusion.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/gamerotvechub.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/ged.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/gmagrotvechub.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/gps_drv_stp.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/gravityhub.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/gyro_common.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/gyrohub.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/gz_ipc_mod.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/gz_irq_mod.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/gz_log_mod.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/gz_main_mod.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/gz_trusty_mod.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/gz_tz_system.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/gz_virtio_mod.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/hwmon.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/imgsensor_isp4_t.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/iommu_gz.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/jd9365tg_i2c.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/jd9365tn_i2c.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/linearacchub.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/load_track.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mac80211.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mag_common.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/maghub.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/main2af.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/main3af.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mainaf.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mali_kbase_mt6768_r49.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mali_mgm_mt6768_r49.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mali_prot_alloc_mt6768_r49.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mcdi.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mdp_drv_mt6768.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mediatek_eem.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mediatek_static_power.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/met.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/met_backlight_api.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/met_emi_api.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/met_gpu_adv_api.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/met_gpu_api.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/met_ipi_api.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/met_mcupm_api.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/met_scmi_api.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/met_sspm_api.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/met_vcore_api.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mt6358-accdet.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mt63xx-debug.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mt6768-mt6358.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mt6768_dcm.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk-afe-external.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk-btcvsd.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk-composite.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk-cqdma.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk-dvfsrc-devfreq.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk-dvfsrc-helper.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk-dvfsrc-start.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk-mbox.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk-pwm.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk-smi-bwc.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk-sp-spk-amp.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk-vcodec-common.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk-vcodec-dec-v1.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk-vcodec-enc-v1.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk-vcu.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_battery_oc_throttling.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_cm_mgr.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_cm_mgr_mt6768.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_cpu_power_throttling.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_dcm.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_disp_sec.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_dynamic_loading_throttling.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_em.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_fpsgo.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_gpu_hal.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_gpu_qos.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_gpufreq_mt6768.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_gpufreq_wrapper_legacy.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_heap_debug.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_ioctl_powerhal.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_ioctl_touch_boost.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_irtx_pwm.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_jpeg.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_low_battery_throttling.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_md_power_throttling.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_mdpm_v1.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_pbm.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_peak_power_budget.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_perf_common.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_perf_ioctl.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_power_gs_v1.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_ppm_v3.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_qos_legacy.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_rpmsg_mbox.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_sec_heap.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_tinysys_ipi.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_u_ether.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/mtk_usb_f_rndis.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/musb_boost.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/nvmem-mt635x-efuse.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/orienthub.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/powerhal_cpu_ctrl.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/reboot-mode.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/rotatvechub.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/rps_perf.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/scheduler.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/scp.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/sec.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/sensorHub.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/sensor_list.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/sensor_probe.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/situation.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/situationhub.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/snd-soc-mt6358.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/snd-soc-mt6768-afe.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/snd-soc-mtk-common.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/sspm_v1.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/step_counter.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/stepsignhub.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/sub2af.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/subaf.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/syscon-reboot-mode.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/t-base-tui.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/thermal_monitor.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/touch_boost.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/trace_mmstat.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/trusted_mem.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/tui-common.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/uload_ind.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/uncali_acchub.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/uncali_gyrohub.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/uncali_maghub.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/v4l2-flash-led-class.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/widevine_driver.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/wlan_drv_gen4m_6768.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/wmt_chrdev_wifi.ko \
    $(LOCAL_DIR)/proprietary/vendor_dlkm/lib/modules/wmt_drv.ko

BOARD_SYSTEM_KERNEL_MODULES := \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/6lowpan.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/8021q.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/9pnet.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/9pnet_fd.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/aqc111.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/asix.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/ax88179_178a.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/bluetooth.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/bsd_comp.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/btbcm.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/btqca.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/btsdio.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/can-bcm.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/can-dev.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/can-gw.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/can-raw.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/can.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/cctrng.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/cdc-acm.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/cdc_eem.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/cdc_ether.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/cdc_ncm.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/diag.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/ftdi_sio.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/gzvm.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/hci_uart.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/hidp.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/ieee802154.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/ieee802154_6lowpan.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/ieee802154_socket.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/kheaders.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/l2tp_core.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/l2tp_ppp.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/libarc4.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/mac802154.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/macsec.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/mii.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/nfc.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/nhc_dest.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/nhc_fragment.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/nhc_hop.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/nhc_ipv6.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/nhc_mobility.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/nhc_routing.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/nhc_udp.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/open-dice.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/ppp_deflate.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/ppp_generic.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/ppp_mppe.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/pppox.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/pps_core.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/pptp.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/ptp.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/ptp_kvm.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/r8152.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/r8153_ecm.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/rfcomm.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/rfkill.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/rtl8150.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/slcan.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/slhc.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/tipc.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/tls.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/usbmon.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/usbnet.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/usbserial.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/vcan.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/vcpu_stall_detector.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/virtio_balloon.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/virtio_blk.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/virtio_console.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/virtio_pci.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/virtio_pci_legacy_dev.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/virtio_pci_modern_dev.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/vmw_vsock_virtio_transport.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/wwan.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/zram.ko \
    $(LOCAL_DIR)/proprietary/system_dlkm/lib/modules/zsmalloc.ko
